name: Production CI/CD

# mainブランチにpushされたら起動する
on:
  push:
    branches:
      - main

jobs:
  # Staging環境でのテスト（deploy.shを実行）
  staging-test:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY:  ${{ secrets.DEV_SSH_KEY }}
      # Staging環境でも deploy.sh を実行するように修正
      - run: ssh -o StrictHostKeyChecking=no ${{ steps.ssh.outputs.SERVER }} "bash /app/na_kondo/deploy.sh staging"

  # Production（本番）環境へのデプロイ
  production-deploy:
    needs: staging-test
    runs-on: ubuntu-latest
    steps:
      - id: ssh-prod
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
          SSH_PORT: ${{ secrets.PROD_SSH_PORT }}
          SSH_USER: ${{ secrets.PROD_SSH_USER }}
          SSH_KEY:  ${{ secrets.PROD_SSH_KEY }}
          
      # 本番サーバーで deploy.sh を実行
      - run: ssh -o StrictHostKeyChecking=no ${{ steps.ssh-prod.outputs.SERVER }} "bash /app/na_kondo/deploy.sh production"
